# Starter pipeline

trigger:
- main

pool:
   Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/prem/parent'
    backendServiceArm: 'Azure subscription 1(2c279754-9ded-4271-a952-14fe81a08ff4)'
    backendAzureRmStorageAccountName: 'rg11stor'
    backendAzureRmContainerName: 'rg11container'
    backendAzureRmKey: 'terraform.tfstate'