# Starter pipeline

trigger:
- main

pool:
   Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/prem/parent'
    backendServiceArm: 'pipelineserco'  # Your Azure service connection name
    backendAzureRmResourceGroupName: 'rg11'  # ⬅️ Add this
    backendAzureRmStorageAccountName: 'rg11stor'
    backendAzureRmContainerName: 'rg11container'
    backendAzureRmKey: 'terraform.tfstate'  # better to give full filename
      # ⬅️ Enables secure auth
