# Starter pipeline

trigger:
- main

pool:
   Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
    backendServiceArm: 'pipelineserco'
    backendAzureRmResourceGroupName: 'rg11'
    backendAzureRmStorageAccountName: 'rg11stor'
    backendAzureRmContainerName: 'rg11container'
    backendAzureRmKey: 'terraform.tfstate'
    useEntraId: true


- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
    environmentServiceNameAzureRM: 'pipelineserco'  # This must be a valid AzureRM service connection
    useEntraId: true

